# Generated by Django 4.2 on 2023-05-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel-order', 'Can cancel order')]},
        ),
    ]
